### ISSUE TITLE
Handle articles with comment.body longer than 10000 characters

### ISSUE THREAD

**Issue by yleong** [fterh/sneakpeek#11]

**Comment by yleong** [comment]
https://www.reddit.com/r/singapore/comments/ai41lj/the_big_read_rise_of_the_machine_how_technology/eeljrcn

Maybe we can split the long comment into multiple comments within a single thread.

**Comment by fterh** [comment]
This is by design. The previous bot got banned because it split long comments into multiple comments and ended up spamming a thread with too many comments. Since most news articles fall below 10,000, I set the limit at 9.9k to accommodate for the version number and other information, and skip articles that are too long.
