### ISSUE TITLE
I have tried to simply some of the code, have a look.

### ISSUE THREAD

**Issue by NoahSee** [fterh/sneakpeek#14]
see:
https://github.com/NoahSee/reddit_commenter
https://www.reddit.com/r/test/comments/ammfbr/testing/

**Comment by NoahSee** [comment]
I cant really do a pull request because, ive used mongodb as the database.

**Comment by fterh** [comment]
Hi, thanks for your effort! Could you quickly walk us through the main enhancements you made?

**Comment by NoahSee** [comment]
I have made the functions in main.py do returns rather than call other functions so that it reads more easily.

1) In your code, main.py does not tell you the overall flow, because scan(subreddit) calls a function that calls yet another function. I made it such that submission.reply () can be seen on main.py. Hence you can see the whole flow on what the code is doing.

2) Ive used MongoDB Atlas. Notce that it is cloud based and uses much less code to work. A collection in MongoDB is simply a list of dictionaries. Ive used a method to return the whole list to check through so it only neeeds to be read once each time main.py runs.

  if any( submission_record['submission_id'] == submission.id for submission_record in submission_records):

does all the work of checking if the submission has already been processed, so you dont need to use qualify()

3) process_submission (WIP) should return a comment if url is valid or None if url is not valid. Im currently testing using straitstimes only.

4) Im currently looking into deploying it on AWS Lambda, but it has a bunch of issues with the external libraries.

**Comment by NoahSee** [comment]
Update: code is operational on lambda.

**Comment by fterh** [comment]
@NoahSee Hi, are you running /u/AngryAngryCat?

**Comment by NoahSee** [comment]
Yes. Ive been letting it run since last night.

**Comment by fterh** [comment]
Can I confirm if you will be running it long-term? I understand that you're running it on a modified codebase (based off this one). I'm just not sure how we're going to coordinate future releases, since I (and the other collaborators) will be working on this repo in the future, and your repo isn't a fork off this so you can't do a git pull.

**Comment by fterh** [comment]
Also, thanks for your breakdown of the changes you've made. I haven't had time to look into that in detail, but I'll definitely get back to that when my schedule clears up. :)

**Comment by NoahSee** [comment]
Im still looking at recoding the handlers to make them more modular and
thus more open sourcable. Think fn(url).

I can walk you through the lambda / mongodb deployent sometime. The actual
web scraping might be too much work for me. Im quite happy as long as it
works for st premium.

Can you explain why @classmethod is used so extensively?

**Comment by NoahSee** [comment]
I have updated the handlers. Have a look.

https://github.com/NoahSee/reddit_commenter

You can coordinate the open sourcing on your repo. I will update the handlers on my repo every once a while. I dont think there needs to be 2 bots running in the long run. Im testing mine for now and ill delete duplicate posts on my end if I see any.

Are you interested in running my version of the code? It uses free tier AWS and mongodb and theres no system infrastructure to mange.

**Comment by fterh** [comment]
I'd prefer to run on my codebase at the moment, although I'm definitely interested to see how I can further improve it once I have time to look at your changes :)

I'm also definitely interested to run on a platform like lambda so I don't have to manage infrastructure. I considered mongodb atlas, but I dropped it because I wanted to get my beta up and running as quickly as I can, and sqlite3 seemed robust enough. It does sound like a great milestone for a future release though!

**Comment by NoahSee** [comment]
Cool. Let me know if you have any questions.

**Comment by xlanor** [comment]
For the bot I dont think you need to deploy it on atlas. I think running it off a local instance on your DO droplet might be more than sufficient.

**Comment by yleong** [comment]
I agree that a DO droplet can more than handle this workload. But I like the idea of `fn(url)`. That way anybody can call the code. Deploying on AWS can solve the uptime issues too. 

However, since `reddit_commenter` has no shared git history with `sneakpeek`, any merge might have to be copied out-of-band. @NoahSee , what license are you releasing `reddit_commenter` under?

**Comment by NoahSee** [comment]
I havent added a licence. You can use whatever you need since most of the code is yours to begin with.

**Comment by NoahSee** [comment]
Hi guys,

I will not be doing any more updates on my repo. It was a good project to do over the CNY break, I really wanted to try out your code and see how I could improve on it.

Also, my bot account got banned. lol
